version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble "
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: echo "testing"
  hithere:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: echo "helllloooo!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
